title: 리더스 합동 법무사 사무소 | 개인회생·개인파산·고소장
description: 수원·용인·화성·평택 지역 개인회생·개인파산·고소장 작성 및 형사합의 상담 - 리더스 합동 법무사 사무소
theme: null

baseurl: ""
url: "https://kstoffice6885.com"

include:
  - assets

collections:
  board:
    output: true
    permalink: /board/:name/

plugins:
  - jekyll-sitemap
  - jekyll-feed

simple_jekyll_search:
  json: true
  url: "/search.json"
  collections:
    board:
      output: true
      limit: 1000
